# Allow local connections (UNIX domain sockets)
local   all             postgres                                trust

# Allow connections from the container itself (127.0.0.1 or ::1)
host    all             all             0.0.0.0/0               trust
host    all             all             ::1/128                 trust

host    all    all    0.0.0.0/0    scram-sha-256
